[build]
  command = "npm run production"
  publish = "dist"

[[plugins]]
    package = "netlify-plugin-11ty"
        [plugins.inputs]
        cache_img = './images'
        cache_img_httpHeader = false

        cache_assets = './cache'
        cache_other = []

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"